import { HeatmapStockItem } from '../types';

export type HeatmapTimeframe = '1d' | '1w' | '1m' | 'ytd' | '1y';

export interface SectorPerformance {
  sector: string;
  avgChange: number;
  stocksCount: number;
  gainersCount: number;
  losersCount: number;
  totalMarketCap: number;
}

export const HEATMAP_DATASET: HeatmapStockItem[] = [
  // 🇮🇹 ITALIA - FTSE MIB & LEADERS
  {
    symbol: 'ISP.MI',
    name: 'Intesa Sanpaolo',
    market: 'IT',
    sector: 'Finanza & Banche',
    price: 3.82,
    currency: 'EUR',
    marketCap: 69.4,
    change1d: 1.35,
    change1w: 2.80,
    change1m: 6.40,
    changeYtd: 34.2,
    change1y: 48.5,
    volume: '28.4M',
    pe: 7.9,
    rsi: 64.2
  },
  {
    symbol: 'UCG.MI',
    name: 'UniCredit',
    market: 'IT',
    sector: 'Finanza & Banche',
    price: 39.50,
    currency: 'EUR',
    marketCap: 64.2,
    change1d: 2.10,
    change1w: 4.50,
    change1m: 9.80,
    changeYtd: 52.6,
    change1y: 72.0,
    volume: '8.2M',
    pe: 7.4,
    rsi: 68.5
  },
  {
    symbol: 'BAMI.MI',
    name: 'Banco BPM',
    market: 'IT',
    sector: 'Finanza & Banche',
    price: 6.45,
    currency: 'EUR',
    marketCap: 9.8,
    change1d: 1.60,
    change1w: 3.10,
    change1m: 5.50,
    changeYtd: 28.4,
    change1y: 42.1,
    volume: '12.1M',
    pe: 7.1,
    rsi: 61.0
  },
  {
    symbol: 'G.MI',
    name: 'Assicurazioni Generali',
    market: 'IT',
    sector: 'Finanza & Banche',
    price: 26.40,
    currency: 'EUR',
    marketCap: 41.2,
    change1d: 0.60,
    change1w: 1.20,
    change1m: 3.40,
    changeYtd: 22.5,
    change1y: 36.8,
    volume: '4.5M',
    pe: 10.4,
    rsi: 59.8
  },
  {
    symbol: 'MB.MI',
    name: 'Mediobanca',
    market: 'IT',
    sector: 'Finanza & Banche',
    price: 14.80,
    currency: 'EUR',
    marketCap: 12.4,
    change1d: 0.85,
    change1w: 1.90,
    change1m: 4.10,
    changeYtd: 18.2,
    change1y: 29.5,
    volume: '3.1M',
    pe: 9.2,
    rsi: 57.5
  },
  {
    symbol: 'ENEL.MI',
    name: 'Enel',
    market: 'IT',
    sector: 'Utilities & Energia',
    price: 6.95,
    currency: 'EUR',
    marketCap: 70.8,
    change1d: 0.72,
    change1w: 1.85,
    change1m: 4.20,
    changeYtd: 15.6,
    change1y: 24.8,
    volume: '22.0M',
    pe: 10.8,
    rsi: 58.4
  },
  {
    symbol: 'TRN.MI',
    name: 'Terna',
    market: 'IT',
    sector: 'Utilities & Energia',
    price: 8.12,
    currency: 'EUR',
    marketCap: 16.3,
    change1d: 0.25,
    change1w: 0.80,
    change1m: 2.10,
    changeYtd: 9.4,
    change1y: 14.5,
    volume: '5.6M',
    pe: 14.5,
    rsi: 54.2
  },
  {
    symbol: 'SRG.MI',
    name: 'Snam',
    market: 'IT',
    sector: 'Utilities & Energia',
    price: 4.55,
    currency: 'EUR',
    marketCap: 15.2,
    change1d: -0.35,
    change1w: 0.40,
    change1m: 1.20,
    changeYtd: 4.8,
    change1y: 8.2,
    volume: '7.8M',
    pe: 13.2,
    rsi: 51.0
  },
  {
    symbol: 'A2A.MI',
    name: 'A2A',
    market: 'IT',
    sector: 'Utilities & Energia',
    price: 2.08,
    currency: 'EUR',
    marketCap: 6.5,
    change1d: 1.45,
    change1w: 2.90,
    change1m: 7.50,
    changeYtd: 21.0,
    change1y: 31.2,
    volume: '9.4M',
    pe: 10.1,
    rsi: 62.4
  },
  {
    symbol: 'ENI.MI',
    name: 'Eni',
    market: 'IT',
    sector: 'Oil & Gas',
    price: 14.20,
    currency: 'EUR',
    marketCap: 45.8,
    change1d: 0.85,
    change1w: -0.60,
    change1m: -2.80,
    changeYtd: -4.5,
    change1y: 6.2,
    volume: '11.5M',
    pe: 8.8,
    rsi: 49.2
  },
  {
    symbol: 'SPM.MI',
    name: 'Saipem',
    market: 'IT',
    sector: 'Oil & Gas',
    price: 2.15,
    currency: 'EUR',
    marketCap: 4.3,
    change1d: -1.80,
    change1w: -3.50,
    change1m: -8.40,
    changeYtd: 42.0,
    change1y: 58.5,
    volume: '34.0M',
    pe: 16.5,
    rsi: 44.0
  },
  {
    symbol: 'RACE.MI',
    name: 'Ferrari',
    market: 'IT',
    sector: 'Lusso & Automotive',
    price: 418.50,
    currency: 'EUR',
    marketCap: 75.6,
    change1d: -0.45,
    change1w: 1.80,
    change1m: 5.40,
    changeYtd: 28.5,
    change1y: 44.2,
    volume: '320K',
    pe: 46.2,
    rsi: 54.0
  },
  {
    symbol: 'STLAM.MI',
    name: 'Stellantis',
    market: 'IT',
    sector: 'Lusso & Automotive',
    price: 12.85,
    currency: 'EUR',
    marketCap: 38.5,
    change1d: -1.20,
    change1w: -4.10,
    change1m: -12.50,
    changeYtd: -38.2,
    change1y: -28.0,
    volume: '18.4M',
    pe: 4.8,
    rsi: 38.6
  },
  {
    symbol: 'BC.MI',
    name: 'Brunello Cucinelli',
    market: 'IT',
    sector: 'Lusso & Automotive',
    price: 92.40,
    currency: 'EUR',
    marketCap: 6.3,
    change1d: 0.95,
    change1w: 2.10,
    change1m: 3.80,
    changeYtd: 8.5,
    change1y: 19.4,
    volume: '210K',
    pe: 42.0,
    rsi: 56.2
  },
  {
    symbol: 'STM.MI',
    name: 'STMicroelectronics',
    market: 'IT',
    sector: 'Tecnologia & Industriale',
    price: 25.60,
    currency: 'EUR',
    marketCap: 23.2,
    change1d: 1.80,
    change1w: -2.40,
    change1m: -9.50,
    changeYtd: -42.5,
    change1y: -36.0,
    volume: '6.2M',
    pe: 11.2,
    rsi: 46.8
  },
  {
    symbol: 'LDO.MI',
    name: 'Leonardo',
    market: 'IT',
    sector: 'Tecnologia & Industriale',
    price: 22.90,
    currency: 'EUR',
    marketCap: 13.2,
    change1d: 2.85,
    change1w: 5.40,
    change1m: 11.20,
    changeYtd: 58.0,
    change1y: 84.5,
    volume: '4.8M',
    pe: 15.6,
    rsi: 71.2
  },
  {
    symbol: 'PRY.MI',
    name: 'Prysmian',
    market: 'IT',
    sector: 'Tecnologia & Industriale',
    price: 64.20,
    currency: 'EUR',
    marketCap: 17.5,
    change1d: 1.45,
    change1w: 3.80,
    change1m: 8.90,
    changeYtd: 54.2,
    change1y: 68.0,
    volume: '2.1M',
    pe: 22.4,
    rsi: 63.4
  },
  {
    symbol: 'AMP.MI',
    name: 'Amplifon',
    market: 'IT',
    sector: 'Sanità & Pharma',
    price: 28.50,
    currency: 'EUR',
    marketCap: 6.4,
    change1d: -0.65,
    change1w: 0.80,
    change1m: -1.50,
    changeYtd: -7.5,
    change1y: -2.1,
    volume: '850K',
    pe: 27.5,
    rsi: 48.0
  },
  {
    symbol: 'REC.MI',
    name: 'Recordati',
    market: 'IT',
    sector: 'Sanità & Pharma',
    price: 52.40,
    currency: 'EUR',
    marketCap: 10.9,
    change1d: 0.40,
    change1w: 1.10,
    change1m: 4.80,
    changeYtd: 12.4,
    change1y: 18.9,
    volume: '480K',
    pe: 21.0,
    rsi: 58.0
  },

  // 🇺🇸 STATI UNITI - S&P 500 & BIG TECH
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corp',
    market: 'US',
    sector: 'Tecnologia & Semiconduttori',
    price: 124.80,
    currency: 'USD',
    marketCap: 3060.0,
    change1d: 3.45,
    change1w: 7.20,
    change1m: 14.50,
    changeYtd: 154.0,
    change1y: 198.0,
    volume: '54.2M',
    pe: 48.5,
    rsi: 64.8
  },
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    market: 'US',
    sector: 'Big Tech & Consumer',
    price: 228.50,
    currency: 'USD',
    marketCap: 3450.0,
    change1d: 0.95,
    change1w: 2.10,
    change1m: 4.80,
    changeYtd: 22.4,
    change1y: 32.5,
    volume: '42.0M',
    pe: 33.5,
    rsi: 57.8
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corp',
    market: 'US',
    sector: 'Cloud & Software',
    price: 432.00,
    currency: 'USD',
    marketCap: 3210.0,
    change1d: 1.15,
    change1w: 2.80,
    change1m: 3.90,
    changeYtd: 18.5,
    change1y: 35.0,
    volume: '21.5M',
    pe: 35.2,
    rsi: 56.4
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    market: 'US',
    sector: 'Internet & Digital Ads',
    price: 165.20,
    currency: 'USD',
    marketCap: 2040.0,
    change1d: -0.80,
    change1w: -1.50,
    change1m: 1.20,
    changeYtd: 19.4,
    change1y: 28.6,
    volume: '19.8M',
    pe: 22.8,
    rsi: 48.5
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    market: 'US',
    sector: 'Big Tech & Consumer',
    price: 188.40,
    currency: 'USD',
    marketCap: 1960.0,
    change1d: 0.70,
    change1w: 3.20,
    change1m: 7.10,
    changeYtd: 26.5,
    change1y: 42.0,
    volume: '31.0M',
    pe: 43.5,
    rsi: 55.2
  },
  {
    symbol: 'META',
    name: 'Meta Platforms',
    market: 'US',
    sector: 'Internet & Digital Ads',
    price: 575.00,
    currency: 'USD',
    marketCap: 1450.0,
    change1d: 1.85,
    change1w: 4.60,
    change1m: 12.40,
    changeYtd: 65.2,
    change1y: 92.0,
    volume: '14.2M',
    pe: 26.8,
    rsi: 67.2
  },
  {
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    market: 'US',
    sector: 'Lusso & Automotive',
    price: 254.00,
    currency: 'USD',
    marketCap: 810.0,
    change1d: -2.40,
    change1w: 5.80,
    change1m: 18.20,
    changeYtd: 3.5,
    change1y: 12.0,
    volume: '68.0M',
    pe: 65.0,
    rsi: 62.0
  },
  {
    symbol: 'BRK-B',
    name: 'Berkshire Hathaway',
    market: 'US',
    sector: 'Finanza & Banche',
    price: 452.00,
    currency: 'USD',
    marketCap: 990.0,
    change1d: 0.35,
    change1w: 1.05,
    change1m: 2.80,
    changeYtd: 28.0,
    change1y: 32.5,
    volume: '3.2M',
    pe: 21.4,
    rsi: 56.0
  },
  {
    symbol: 'JPM',
    name: 'JPMorgan Chase',
    market: 'US',
    sector: 'Finanza & Banche',
    price: 212.00,
    currency: 'USD',
    marketCap: 605.0,
    change1d: 1.25,
    change1w: 2.40,
    change1m: 5.60,
    changeYtd: 26.2,
    change1y: 45.0,
    volume: '8.4M',
    pe: 11.8,
    rsi: 62.5
  },
  {
    symbol: 'LLY',
    name: 'Eli Lilly & Co',
    market: 'US',
    sector: 'Sanità & Pharma',
    price: 895.00,
    currency: 'USD',
    marketCap: 850.0,
    change1d: 2.15,
    change1w: 4.80,
    change1m: 8.20,
    changeYtd: 55.0,
    change1y: 78.5,
    volume: '2.8M',
    pe: 68.0,
    rsi: 63.5
  },
  {
    symbol: 'JNJ',
    name: 'Johnson & Johnson',
    market: 'US',
    sector: 'Sanità & Pharma',
    price: 162.50,
    currency: 'USD',
    marketCap: 390.0,
    change1d: -0.20,
    change1w: 0.50,
    change1m: 1.80,
    changeYtd: 4.2,
    change1y: 6.8,
    volume: '5.2M',
    pe: 17.2,
    rsi: 51.0
  },
  {
    symbol: 'XOM',
    name: 'Exxon Mobil Corp',
    market: 'US',
    sector: 'Oil & Gas',
    price: 116.80,
    currency: 'USD',
    marketCap: 465.0,
    change1d: 0.45,
    change1w: -1.20,
    change1m: -0.80,
    changeYtd: 17.5,
    change1y: 11.2,
    volume: '14.0M',
    pe: 13.8,
    rsi: 52.0
  },

  // 🇪🇺 EUROPA - EURO STOXX 50 CHAMPIONS
  {
    symbol: 'ASML.AS',
    name: 'ASML Holding',
    market: 'EU',
    sector: 'Tecnologia & Semiconduttori',
    price: 765.00,
    currency: 'EUR',
    marketCap: 302.0,
    change1d: 2.40,
    change1w: -1.80,
    change1m: -8.50,
    changeYtd: 14.5,
    change1y: 35.0,
    volume: '1.4M',
    pe: 41.0,
    rsi: 58.2
  },
  {
    symbol: 'NOVO-B.CO',
    name: 'Novo Nordisk',
    market: 'EU',
    sector: 'Sanità & Pharma',
    price: 815.00,
    currency: 'DKK',
    marketCap: 525.0,
    change1d: 1.10,
    change1w: 2.50,
    change1m: 4.80,
    changeYtd: 21.0,
    change1y: 42.0,
    volume: '1.8M',
    pe: 36.5,
    rsi: 53.5
  },
  {
    symbol: 'MC.PA',
    name: 'LVMH',
    market: 'EU',
    sector: 'Lusso & Automotive',
    price: 642.00,
    currency: 'EUR',
    marketCap: 320.0,
    change1d: -1.15,
    change1w: -2.80,
    change1m: -4.50,
    changeYtd: -12.4,
    change1y: -8.5,
    volume: '420K',
    pe: 21.8,
    rsi: 42.0
  },
  {
    symbol: 'SAP.DE',
    name: 'SAP SE',
    market: 'EU',
    sector: 'Cloud & Software',
    price: 198.00,
    currency: 'EUR',
    marketCap: 232.0,
    change1d: 1.65,
    change1w: 3.40,
    change1m: 7.80,
    changeYtd: 44.5,
    change1y: 62.0,
    volume: '2.4M',
    pe: 38.0,
    rsi: 66.8
  },
  {
    symbol: 'TTE.PA',
    name: 'TotalEnergies',
    market: 'EU',
    sector: 'Oil & Gas',
    price: 61.20,
    currency: 'EUR',
    marketCap: 145.0,
    change1d: 0.40,
    change1w: -0.85,
    change1m: -1.40,
    changeYtd: 2.5,
    change1y: 8.4,
    volume: '4.8M',
    pe: 7.6,
    rsi: 52.0
  },
  {
    symbol: 'AIR.PA',
    name: 'Airbus SE',
    market: 'EU',
    sector: 'Tecnologia & Industriale',
    price: 136.50,
    currency: 'EUR',
    marketCap: 108.0,
    change1d: -0.75,
    change1w: 1.20,
    change1m: 3.10,
    changeYtd: -2.4,
    change1y: 11.5,
    volume: '1.9M',
    pe: 26.5,
    rsi: 49.5
  },

  // 🪙 CRYPTO & COMMODITIES
  {
    symbol: 'BTC-USD',
    name: 'Bitcoin',
    market: 'CRYPTO_COMMODITY',
    sector: 'Crypto & Assets Digitali',
    price: 64500.00,
    currency: 'USD',
    marketCap: 1270.0,
    change1d: 2.85,
    change1w: 6.40,
    change1m: 11.80,
    changeYtd: 54.0,
    change1y: 142.0,
    volume: '$28.5B',
    rsi: 63.8
  },
  {
    symbol: 'ETH-USD',
    name: 'Ethereum',
    market: 'CRYPTO_COMMODITY',
    sector: 'Crypto & Assets Digitali',
    price: 2650.00,
    currency: 'USD',
    marketCap: 318.0,
    change1d: 1.95,
    change1w: 4.80,
    change1m: 8.20,
    changeYtd: 16.5,
    change1y: 65.0,
    volume: '$14.2B',
    rsi: 58.4
  },
  {
    symbol: 'SOL-USD',
    name: 'Solana',
    market: 'CRYPTO_COMMODITY',
    sector: 'Crypto & Assets Digitali',
    price: 154.20,
    currency: 'USD',
    marketCap: 72.5,
    change1d: 4.20,
    change1w: 12.50,
    change1m: 22.0,
    changeYtd: 52.0,
    change1y: 480.0,
    volume: '$3.8B',
    rsi: 69.2
  },
  {
    symbol: 'GC=F',
    name: 'Oro Spot (Gold)',
    market: 'CRYPTO_COMMODITY',
    sector: 'Materie Prime & Metalli',
    price: 2665.00,
    currency: 'USD',
    marketCap: 17500.0,
    change1d: 0.65,
    change1w: 1.80,
    change1m: 6.40,
    changeYtd: 29.5,
    change1y: 42.0,
    volume: '$180B',
    rsi: 74.5
  },
  {
    symbol: 'CL=F',
    name: 'Petrolio Greggio (WTI)',
    market: 'CRYPTO_COMMODITY',
    sector: 'Materie Prime & Metalli',
    price: 68.80,
    currency: 'USD',
    marketCap: 2500.0,
    change1d: -1.45,
    change1w: -3.80,
    change1m: -7.20,
    changeYtd: -4.5,
    change1y: -22.0,
    volume: '$45B',
    rsi: 41.2
  },
  {
    symbol: 'SI=F',
    name: 'Argento (Silver)',
    market: 'CRYPTO_COMMODITY',
    sector: 'Materie Prime & Metalli',
    price: 31.80,
    currency: 'USD',
    marketCap: 1800.0,
    change1d: 1.85,
    change1w: 4.50,
    change1m: 11.20,
    changeYtd: 36.5,
    change1y: 48.0,
    volume: '$24B',
    rsi: 68.0
  }
];

export const heatmapDataService = {
  getAll(): HeatmapStockItem[] {
    return HEATMAP_DATASET;
  },

  getChangeByTimeframe(item: HeatmapStockItem, tf: HeatmapTimeframe): number {
    switch (tf) {
      case '1d': return item.change1d;
      case '1w': return item.change1w;
      case '1m': return item.change1m;
      case 'ytd': return item.changeYtd;
      case '1y': return item.change1y;
      default: return item.change1d;
    }
  },

  getSectorStats(items: HeatmapStockItem[], tf: HeatmapTimeframe): SectorPerformance[] {
    const sectorMap: Record<string, { totalChg: number; count: number; gainers: number; losers: number; cap: number }> = {};

    items.forEach(item => {
      const chg = this.getChangeByTimeframe(item, tf);
      if (!sectorMap[item.sector]) {
        sectorMap[item.sector] = { totalChg: 0, count: 0, gainers: 0, losers: 0, cap: 0 };
      }
      sectorMap[item.sector].totalChg += chg;
      sectorMap[item.sector].count += 1;
      sectorMap[item.sector].cap += item.marketCap;
      if (chg > 0) sectorMap[item.sector].gainers += 1;
      else if (chg < 0) sectorMap[item.sector].losers += 1;
    });

    return Object.entries(sectorMap)
      .map(([sector, data]) => ({
        sector,
        avgChange: Number((data.totalChg / data.count).toFixed(2)),
        stocksCount: data.count,
        gainersCount: data.gainers,
        losersCount: data.losers,
        totalMarketCap: Number(data.cap.toFixed(1))
      }))
      .sort((a, b) => b.avgChange - a.avgChange);
  }
};
