import { ScreenerStockItem, ScreenerFilterState } from '../types';

export interface ScreenerPresetModel {
  id: string;
  name: string;
  badge: string;
  author: string;
  icon: string;
  color: string;
  description: string;
  criteriaSummary: string[];
  filters: Partial<ScreenerFilterState>;
}

export const SCREENER_PRESET_MODELS: ScreenerPresetModel[] = [
  {
    id: 'all',
    name: 'Tutte le Azioni',
    badge: 'ALL',
    author: 'Mercato Globale',
    icon: 'Globe',
    color: 'from-blue-600 to-indigo-600',
    description: 'Nessun filtro restrittivo: visualizza e ordina l\'intero universo azionario per qualsiasi metrica.',
    criteriaSummary: ['Tutti i mercati', 'Tutti i settori', 'Nessun limite di multiplo'],
    filters: {}
  },
  {
    id: 'buffett',
    name: 'Modello Warren Buffett',
    badge: 'Moat & Quality',
    author: 'Berkshire Hathaway',
    icon: 'Award',
    color: 'from-amber-600 to-yellow-600',
    description: 'Aziende eccellenti con elevato fossato competitivo (Economic Moat), redditività del capitale (ROE > 15%), indebitamento contenuto e flussi di cassa solidi.',
    criteriaSummary: [
      'ROE ≥ 15%',
      'Debt / Equity ≤ 1.0',
      'Margine Operativo ≥ 15%',
      'P/E ≤ 25',
      'Flusso di cassa (P/FCF) sostenibile'
    ],
    filters: {
      minRoe: 15,
      maxDebtToEquity: 1.0,
      minOperatingMargin: 15,
      maxPe: 25
    }
  },
  {
    id: 'investing_pro',
    name: 'Modello InvestingPro Fair Value',
    badge: 'Undervalued Quality',
    author: 'Investing.pro & DCF Models',
    icon: 'Sparkles',
    color: 'from-emerald-600 to-teal-600',
    description: 'Titoli con elevato potenziale di rialzo rispetto al Fair Value stimato dai modelli proprietari (>15%) e punteggio di salute finanziaria superiore alla media.',
    criteriaSummary: [
      'Potenziale Fair Value Upside ≥ 15%',
      'Salute Finanziaria ≥ 3.5 / 5.0',
      'P/E ≤ 22',
      'Margine Operativo ≥ 10%'
    ],
    filters: {
      minFairValueUpside: 15,
      maxPe: 22,
      minOperatingMargin: 10
    }
  },
  {
    id: 'value',
    name: 'Modello Deep Value & Graham',
    badge: 'Value Investing',
    author: 'Benjamin Graham & Peter Lynch',
    icon: 'Shield',
    color: 'from-purple-600 to-indigo-600',
    description: 'Titoli a forte sconto con multipli compressi (P/E e P/B bassi), PEG contenuto e solido stato patrimoniale difensivo con margine di sicurezza.',
    criteriaSummary: [
      'P/E ≤ 15',
      'P/B ≤ 2.0',
      'PEG Ratio ≤ 1.2',
      'Current Ratio ≥ 1.2',
      'Dividend Yield ≥ 2.0%'
    ],
    filters: {
      maxPe: 15,
      maxPb: 2.0,
      maxPeg: 1.2,
      minCurrentRatio: 1.2,
      minDividendYield: 2.0
    }
  },
  {
    id: 'growth',
    name: 'Modello High Growth & Innovators',
    badge: 'CANSLIM Growth',
    author: 'William O\'Neil & Tech Momentum',
    icon: 'Rocket',
    color: 'from-cyan-600 to-blue-600',
    description: 'Aziende leader ad alta espansione con forte crescita del fatturato YoY (>15%), crescita degli utili EPS accelerata e margini lordi elevati.',
    criteriaSummary: [
      'Crescita Ricavi YoY ≥ 15%',
      'Crescita Utili EPS YoY ≥ 20%',
      'Margine Lordo ≥ 35%',
      'Prezzo sopra SMA 50 o SMA 200'
    ],
    filters: {
      minRevenueGrowth: 15,
      minEpsGrowth: 20,
      smaTrend: 'ABOVE_200'
    }
  },
  {
    id: 'dalio',
    name: 'Modello Ray Dalio All-Weather',
    badge: 'Defensive & Resilient',
    author: 'Bridgewater Associates',
    icon: 'ShieldCheck',
    color: 'from-emerald-700 to-green-700',
    description: 'Titoli difensivi resilienti con bassa volatilità (Beta < 0.90), solido bilancio e capacità di generare rendimenti stabili in tutte le fasi del ciclo economico.',
    criteriaSummary: [
      'Beta Volatilità ≤ 0.85',
      'Debt / Equity ≤ 0.8',
      'Dividend Yield ≥ 2.5%',
      'Margine Operativo ≥ 12%'
    ],
    filters: {
      maxBeta: 0.85,
      maxDebtToEquity: 0.8,
      minDividendYield: 2.5,
      minOperatingMargin: 12
    }
  },
  {
    id: 'dividends',
    name: 'Modello Dividend Aristocrats & Cash Cows',
    badge: 'High Yield',
    author: 'Dividend Growth Strategy',
    icon: 'DollarSign',
    color: 'from-amber-700 to-yellow-700',
    description: 'Macchine da dividendo con cedole generose (>4.0%), payout ratio sostenibile (<75%) e flusso di cassa libero costante nel tempo.',
    criteriaSummary: [
      'Dividend Yield ≥ 4.0%',
      'Payout Ratio ≤ 75%',
      'Debt / Equity ≤ 1.2',
      'ROE ≥ 10%'
    ],
    filters: {
      minDividendYield: 4.0,
      maxPayoutRatio: 75,
      maxDebtToEquity: 1.2,
      minRoe: 10
    }
  },
  {
    id: 'peter_lynch',
    name: 'Modello Peter Lynch (GARP & PEG)',
    badge: 'Growth At Reasonable Price',
    author: 'Fidelity Magellan Fund',
    icon: 'TrendingUp',
    color: 'from-blue-600 to-cyan-600',
    description: 'Filosofia Peter Lynch: cerca società in solida espansione con PEG ratio contenuto (≤ 1.0), crescita EPS sostenibile (≥ 12%), debito controllato e margine operativo solido.',
    criteriaSummary: [
      'PEG Ratio ≤ 1.0',
      'Crescita Utili EPS ≥ 12%',
      'Debt / Equity ≤ 0.8',
      'P/E ≤ 22',
      'ROE ≥ 14%'
    ],
    filters: {
      maxPeg: 1.0,
      minEpsGrowth: 12,
      maxDebtToEquity: 0.8,
      maxPe: 22,
      minRoe: 14
    }
  },
  {
    id: 'graham_defensive',
    name: 'Modello Benjamin Graham (Deep Value)',
    badge: 'Graham Number & Margin of Safety',
    author: 'Father of Value Investing',
    icon: 'Shield',
    color: 'from-amber-700 to-yellow-800',
    description: 'Criteri difensivi di Benjamin Graham: multipli compressi (P/E ≤ 15, P/B ≤ 1.5, prodotto P/E × P/B ≤ 22.5), solida liquidità corrente (Current Ratio ≥ 1.5) e basso indebitamento.',
    criteriaSummary: [
      'P/E ≤ 15',
      'P/B ≤ 1.5',
      'Current Ratio ≥ 1.5',
      'Debt / Equity ≤ 0.6',
      'Dividend Yield ≥ 2.5%'
    ],
    filters: {
      maxPe: 15,
      maxPb: 1.5,
      minCurrentRatio: 1.5,
      maxDebtToEquity: 0.6,
      minDividendYield: 2.5
    }
  },
  {
    id: 'quality_magic',
    name: 'Modello Magic Quality (ROIC & FCF Yield)',
    badge: 'High ROIC & Free Cash Flow',
    author: 'Joel Greenblatt & Quality Compounders',
    icon: 'Sparkles',
    color: 'from-emerald-600 to-teal-700',
    description: 'Seleziona campioni di redditività del capitale investito (ROIC elevato), robusta generazione di Free Cash Flow Yield e punteggio di bilancio Piotroski F-Score elevato.',
    criteriaSummary: [
      'ROIC ≥ 15%',
      'FCF Yield ≥ 5.0%',
      'Piotroski Score ≥ 7',
      'Margine Operativo ≥ 15%',
      'Debt / Equity ≤ 1.0'
    ],
    filters: {
      minRoic: 15,
      minFcfYield: 5.0,
      minPiotroskiScore: 7,
      minOperatingMargin: 15,
      maxDebtToEquity: 1.0
    }
  },
  {
    id: 'momentum',
    name: 'Modello Momentum & Trend Breakout',
    badge: 'Trend Following',
    author: 'Technical Breakout',
    icon: 'TrendingUp',
    color: 'from-rose-600 to-orange-600',
    description: 'Titoli in forte trend rialzista tecnico con prezzo stabilmente sopra le medie a 50 e 200 giorni ed RSI non in ipervenduto.',
    criteriaSummary: [
      'Prezzo > SMA 50 e SMA 200',
      'RSI (14) tra 50 e 72',
      'Beta ≥ 1.0',
      'Crescita Ricavi ≥ 10%'
    ],
    filters: {
      smaTrend: 'ABOVE_50_200',
      minRsi: 50,
      maxRsi: 72,
      minBeta: 1.0
    }
  }
];

export const INITIAL_SCREENER_STOCKS: ScreenerStockItem[] = [
  {
    symbol: 'ENEL.MI',
    name: 'Enel S.p.A.',
    exchange: 'Borsa Italiana (MTA)',
    country: 'IT',
    sector: 'Utilities & Energia Rinnovabile',
    industry: 'Utilities - Regulated Electric',
    price: 6.95,
    changePct: 0.72,
    marketCap: 70.8,
    marketCapCategory: 'Large',
    pe: 10.8,
    forwardPe: 9.8,
    pb: 1.85,
    peg: 0.95,
    evEbitda: 6.2,
    pcf: 5.4,
    roe: 17.2,
    roa: 4.1,
    operatingMargin: 18.5,
    grossMargin: 38.2,
    revenueGrowthYoY: 8.5,
    epsGrowthYoY: 14.2,
    debtToEquity: 0.95,
    currentRatio: 1.25,
    dividendYield: 6.2,
    payoutRatio: 65,
    rsi14: 58.4,
    beta: 0.75,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 8.40,
    fairValueUpside: 20.8,
    buffettScore: 78,
    investingProScore: 4.2,
    dalioScore: 88,
    growthScore: 62,
    valueScore: 86
  },
  {
    symbol: 'ISP.MI',
    name: 'Intesa Sanpaolo S.p.A.',
    exchange: 'Borsa Italiana (MTA)',
    country: 'IT',
    sector: 'Finanza & Bancario',
    industry: 'Banks - Diversified',
    price: 3.82,
    changePct: 1.35,
    marketCap: 69.4,
    marketCapCategory: 'Large',
    pe: 7.9,
    forwardPe: 7.2,
    pb: 1.15,
    peg: 0.72,
    evEbitda: 5.8,
    pcf: 4.9,
    roe: 16.8,
    roa: 1.2,
    operatingMargin: 42.5,
    grossMargin: 65.0,
    revenueGrowthYoY: 12.4,
    epsGrowthYoY: 18.6,
    debtToEquity: 0.70,
    currentRatio: 1.40,
    dividendYield: 8.1,
    payoutRatio: 68,
    rsi14: 64.2,
    beta: 0.88,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 4.60,
    fairValueUpside: 20.4,
    buffettScore: 84,
    investingProScore: 4.4,
    dalioScore: 82,
    growthScore: 70,
    valueScore: 92
  },
  {
    symbol: 'UCG.MI',
    name: 'UniCredit S.p.A.',
    exchange: 'Borsa Italiana (MTA)',
    country: 'IT',
    sector: 'Finanza & Bancario',
    industry: 'Banks - Regional',
    price: 39.50,
    changePct: 2.10,
    marketCap: 64.2,
    marketCapCategory: 'Large',
    pe: 7.4,
    forwardPe: 6.8,
    pb: 1.05,
    peg: 0.65,
    evEbitda: 5.2,
    pcf: 4.5,
    roe: 18.9,
    roa: 1.4,
    operatingMargin: 46.0,
    grossMargin: 68.5,
    revenueGrowthYoY: 15.2,
    epsGrowthYoY: 24.8,
    debtToEquity: 0.65,
    currentRatio: 1.35,
    dividendYield: 7.4,
    payoutRatio: 55,
    rsi14: 68.5,
    beta: 1.15,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 48.00,
    fairValueUpside: 21.5,
    buffettScore: 82,
    investingProScore: 4.6,
    dalioScore: 74,
    growthScore: 78,
    valueScore: 94
  },
  {
    symbol: 'RACE.MI',
    name: 'Ferrari N.V.',
    exchange: 'Borsa Italiana (MTA)',
    country: 'IT',
    sector: 'Beni di Lusso & Automotive',
    industry: 'Auto Manufacturers - Luxury',
    price: 418.50,
    changePct: -0.45,
    marketCap: 75.6,
    marketCapCategory: 'Large',
    pe: 46.2,
    forwardPe: 38.5,
    pb: 22.4,
    peg: 2.8,
    evEbitda: 28.5,
    pcf: 32.0,
    roe: 48.6,
    roa: 16.5,
    operatingMargin: 27.8,
    grossMargin: 49.8,
    revenueGrowthYoY: 17.2,
    epsGrowthYoY: 22.4,
    debtToEquity: 0.85,
    currentRatio: 1.65,
    dividendYield: 0.6,
    payoutRatio: 30,
    rsi14: 54.0,
    beta: 0.92,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 435.00,
    fairValueUpside: 3.9,
    buffettScore: 89,
    investingProScore: 3.8,
    dalioScore: 70,
    growthScore: 86,
    valueScore: 42
  },
  {
    symbol: 'ENI.MI',
    name: 'Eni S.p.A.',
    exchange: 'Borsa Italiana (MTA)',
    country: 'IT',
    sector: 'Energia & Oil & Gas',
    industry: 'Oil & Gas Integrated',
    price: 14.20,
    changePct: 0.85,
    marketCap: 45.8,
    marketCapCategory: 'Large',
    pe: 8.8,
    forwardPe: 7.9,
    pb: 0.88,
    peg: 0.82,
    evEbitda: 3.6,
    pcf: 3.9,
    roe: 13.5,
    roa: 5.2,
    operatingMargin: 14.8,
    grossMargin: 32.4,
    revenueGrowthYoY: -4.2,
    epsGrowthYoY: 6.8,
    debtToEquity: 0.45,
    currentRatio: 1.42,
    dividendYield: 7.0,
    payoutRatio: 58,
    rsi14: 49.2,
    beta: 0.82,
    priceAboveSma50: false,
    priceAboveSma200: true,
    fairValue: 18.20,
    fairValueUpside: 28.1,
    buffettScore: 74,
    investingProScore: 4.1,
    dalioScore: 84,
    growthScore: 48,
    valueScore: 90
  },
  {
    symbol: 'STLAM.MI',
    name: 'Stellantis N.V.',
    exchange: 'Borsa Italiana (MTA)',
    country: 'IT',
    sector: 'Automotive & Mobilità',
    industry: 'Auto Manufacturers',
    price: 12.85,
    changePct: -1.20,
    marketCap: 38.5,
    marketCapCategory: 'Large',
    pe: 4.8,
    forwardPe: 5.2,
    pb: 0.48,
    peg: 0.55,
    evEbitda: 1.8,
    pcf: 2.5,
    roe: 14.2,
    roa: 6.0,
    operatingMargin: 8.5,
    grossMargin: 19.5,
    revenueGrowthYoY: -11.5,
    epsGrowthYoY: -18.2,
    debtToEquity: 0.35,
    currentRatio: 1.38,
    dividendYield: 9.8,
    payoutRatio: 45,
    rsi14: 38.6,
    beta: 1.45,
    priceAboveSma50: false,
    priceAboveSma200: false,
    fairValue: 18.50,
    fairValueUpside: 43.9,
    buffettScore: 68,
    investingProScore: 3.6,
    dalioScore: 60,
    growthScore: 38,
    valueScore: 96
  },
  {
    symbol: 'STM.MI',
    name: 'STMicroelectronics N.V.',
    exchange: 'Borsa Italiana (MTA)',
    country: 'IT',
    sector: 'Tecnologia & Semiconduttori',
    industry: 'Semiconductors',
    price: 25.60,
    changePct: 1.80,
    marketCap: 23.2,
    marketCapCategory: 'Mid',
    pe: 11.2,
    forwardPe: 12.8,
    pb: 1.65,
    peg: 1.10,
    evEbitda: 5.4,
    pcf: 6.2,
    roe: 18.4,
    roa: 11.8,
    operatingMargin: 21.0,
    grossMargin: 42.5,
    revenueGrowthYoY: -6.8,
    epsGrowthYoY: -12.4,
    debtToEquity: 0.22,
    currentRatio: 2.85,
    dividendYield: 1.4,
    payoutRatio: 15,
    rsi14: 46.8,
    beta: 1.38,
    priceAboveSma50: false,
    priceAboveSma200: false,
    fairValue: 36.50,
    fairValueUpside: 42.5,
    buffettScore: 76,
    investingProScore: 4.0,
    dalioScore: 72,
    growthScore: 68,
    valueScore: 84
  },
  {
    symbol: 'LDO.MI',
    name: 'Leonardo S.p.A.',
    exchange: 'Borsa Italiana (MTA)',
    country: 'IT',
    sector: 'Aerospazio, Difesa & Sicurezza',
    industry: 'Aerospace & Defense',
    price: 22.90,
    changePct: 2.85,
    marketCap: 13.2,
    marketCapCategory: 'Mid',
    pe: 15.6,
    forwardPe: 13.2,
    pb: 1.82,
    peg: 0.88,
    evEbitda: 7.9,
    pcf: 9.2,
    roe: 14.5,
    roa: 4.8,
    operatingMargin: 10.4,
    grossMargin: 24.5,
    revenueGrowthYoY: 14.8,
    epsGrowthYoY: 26.5,
    debtToEquity: 0.58,
    currentRatio: 1.28,
    dividendYield: 1.6,
    payoutRatio: 22,
    rsi14: 71.2,
    beta: 1.05,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 27.50,
    fairValueUpside: 20.0,
    buffettScore: 75,
    investingProScore: 4.1,
    dalioScore: 76,
    growthScore: 84,
    valueScore: 78
  },
  {
    symbol: 'PRY.MI',
    name: 'Prysmian S.p.A.',
    exchange: 'Borsa Italiana (MTA)',
    country: 'IT',
    sector: 'Industriale & Cavi Elettrici',
    industry: 'Electrical Equipment & Parts',
    price: 64.20,
    changePct: 1.45,
    marketCap: 17.5,
    marketCapCategory: 'Mid',
    pe: 22.4,
    forwardPe: 18.5,
    pb: 3.40,
    peg: 1.25,
    evEbitda: 11.2,
    pcf: 14.0,
    roe: 18.2,
    roa: 6.8,
    operatingMargin: 9.8,
    grossMargin: 28.5,
    revenueGrowthYoY: 11.2,
    epsGrowthYoY: 19.4,
    debtToEquity: 0.72,
    currentRatio: 1.35,
    dividendYield: 1.2,
    payoutRatio: 25,
    rsi14: 63.4,
    beta: 1.12,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 72.00,
    fairValueUpside: 12.1,
    buffettScore: 77,
    investingProScore: 3.9,
    dalioScore: 71,
    growthScore: 82,
    valueScore: 68
  },
  {
    symbol: 'G.MI',
    name: 'Assicurazioni Generali S.p.A.',
    exchange: 'Borsa Italiana (MTA)',
    country: 'IT',
    sector: 'Assicurazioni & Wealth Management',
    industry: 'Insurance - Multi-line',
    price: 26.40,
    changePct: 0.60,
    marketCap: 41.2,
    marketCapCategory: 'Large',
    pe: 10.4,
    forwardPe: 9.5,
    pb: 1.32,
    peg: 0.85,
    evEbitda: 6.8,
    pcf: 5.8,
    roe: 15.6,
    roa: 1.8,
    operatingMargin: 12.5,
    grossMargin: 45.0,
    revenueGrowthYoY: 7.8,
    epsGrowthYoY: 11.5,
    debtToEquity: 0.62,
    currentRatio: 1.45,
    dividendYield: 5.5,
    payoutRatio: 60,
    rsi14: 59.8,
    beta: 0.78,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 31.00,
    fairValueUpside: 17.4,
    buffettScore: 82,
    investingProScore: 4.3,
    dalioScore: 86,
    growthScore: 64,
    valueScore: 88
  },

  // 🇺🇸 STATI UNITI
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Tecnologia Consumer & Ecosistema',
    industry: 'Consumer Electronics',
    price: 228.50,
    changePct: 0.95,
    marketCap: 3450.0,
    marketCapCategory: 'Mega',
    pe: 33.5,
    forwardPe: 28.2,
    pb: 48.0,
    peg: 2.4,
    evEbitda: 24.2,
    pcf: 26.5,
    roe: 147.2,
    roa: 28.5,
    operatingMargin: 31.4,
    grossMargin: 46.2,
    revenueGrowthYoY: 6.1,
    epsGrowthYoY: 12.8,
    debtToEquity: 1.45,
    currentRatio: 1.05,
    dividendYield: 0.45,
    payoutRatio: 16,
    rsi14: 57.8,
    beta: 0.89,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 245.00,
    fairValueUpside: 7.2,
    buffettScore: 92,
    investingProScore: 4.1,
    dalioScore: 78,
    growthScore: 79,
    valueScore: 56
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Cloud, Software & AI Enterprise',
    industry: 'Software - Infrastructure',
    price: 432.00,
    changePct: 1.15,
    marketCap: 3210.0,
    marketCapCategory: 'Mega',
    pe: 35.2,
    forwardPe: 29.5,
    pb: 12.2,
    peg: 2.1,
    evEbitda: 23.0,
    pcf: 25.8,
    roe: 38.5,
    roa: 19.2,
    operatingMargin: 44.6,
    grossMargin: 69.8,
    revenueGrowthYoY: 15.3,
    epsGrowthYoY: 18.2,
    debtToEquity: 0.42,
    currentRatio: 1.35,
    dividendYield: 0.75,
    payoutRatio: 26,
    rsi14: 56.4,
    beta: 0.90,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 485.00,
    fairValueUpside: 12.3,
    buffettScore: 94,
    investingProScore: 4.5,
    dalioScore: 80,
    growthScore: 88,
    valueScore: 60
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'AI Chips, GPU & Calcolo Accelerato',
    industry: 'Semiconductors',
    price: 124.80,
    changePct: 3.45,
    marketCap: 3060.0,
    marketCapCategory: 'Mega',
    pe: 48.5,
    forwardPe: 34.0,
    pb: 38.5,
    peg: 1.15,
    evEbitda: 36.2,
    pcf: 41.0,
    roe: 115.0,
    roa: 55.4,
    operatingMargin: 64.9,
    grossMargin: 75.3,
    revenueGrowthYoY: 122.4,
    epsGrowthYoY: 152.0,
    debtToEquity: 0.18,
    currentRatio: 4.15,
    dividendYield: 0.03,
    payoutRatio: 2,
    rsi14: 64.8,
    beta: 1.68,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 148.00,
    fairValueUpside: 18.6,
    buffettScore: 86,
    investingProScore: 4.6,
    dalioScore: 65,
    growthScore: 98,
    valueScore: 48
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc. (Google)',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Search, Cloud, AI & Digital Ads',
    industry: 'Internet Content & Information',
    price: 165.20,
    changePct: -0.80,
    marketCap: 2040.0,
    marketCapCategory: 'Mega',
    pe: 22.8,
    forwardPe: 19.4,
    pb: 6.8,
    peg: 1.12,
    evEbitda: 15.4,
    pcf: 17.2,
    roe: 31.5,
    roa: 21.0,
    operatingMargin: 32.4,
    grossMargin: 57.5,
    revenueGrowthYoY: 13.8,
    epsGrowthYoY: 28.5,
    debtToEquity: 0.10,
    currentRatio: 2.10,
    dividendYield: 0.48,
    payoutRatio: 11,
    rsi14: 48.5,
    beta: 1.05,
    priceAboveSma50: false,
    priceAboveSma200: true,
    fairValue: 205.00,
    fairValueUpside: 24.1,
    buffettScore: 91,
    investingProScore: 4.7,
    dalioScore: 82,
    growthScore: 85,
    valueScore: 78
  },
  {
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'Social Media, Metaverse & AI Ads',
    industry: 'Internet Content & Information',
    price: 575.00,
    changePct: 1.85,
    marketCap: 1450.0,
    marketCapCategory: 'Mega',
    pe: 26.8,
    forwardPe: 22.5,
    pb: 8.9,
    peg: 1.08,
    evEbitda: 17.0,
    pcf: 19.5,
    roe: 36.8,
    roa: 22.4,
    operatingMargin: 41.2,
    grossMargin: 81.8,
    revenueGrowthYoY: 22.1,
    epsGrowthYoY: 73.0,
    debtToEquity: 0.24,
    currentRatio: 2.65,
    dividendYield: 0.35,
    payoutRatio: 9,
    rsi14: 67.2,
    beta: 1.22,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 650.00,
    fairValueUpside: 13.0,
    buffettScore: 88,
    investingProScore: 4.5,
    dalioScore: 74,
    growthScore: 92,
    valueScore: 72
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    exchange: 'NASDAQ',
    country: 'US',
    sector: 'E-Commerce, AWS Cloud & Logistica',
    industry: 'Internet Retail',
    price: 188.40,
    changePct: 0.70,
    marketCap: 1960.0,
    marketCapCategory: 'Mega',
    pe: 43.5,
    forwardPe: 31.0,
    pb: 8.2,
    peg: 1.35,
    evEbitda: 18.2,
    pcf: 16.8,
    roe: 21.8,
    roa: 8.5,
    operatingMargin: 9.9,
    grossMargin: 48.9,
    revenueGrowthYoY: 10.1,
    epsGrowthYoY: 94.0,
    debtToEquity: 0.58,
    currentRatio: 1.08,
    dividendYield: 0.0,
    payoutRatio: 0,
    rsi14: 55.2,
    beta: 1.15,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 225.00,
    fairValueUpside: 19.4,
    buffettScore: 83,
    investingProScore: 4.2,
    dalioScore: 75,
    growthScore: 89,
    valueScore: 62
  },
  {
    symbol: 'BRK-B',
    name: 'Berkshire Hathaway Inc.',
    exchange: 'NYSE',
    country: 'US',
    sector: 'Conglomerata, Assicurazioni & Energia',
    industry: 'Financial Conglomerate',
    price: 452.00,
    changePct: 0.35,
    marketCap: 990.0,
    marketCapCategory: 'Mega',
    pe: 21.4,
    forwardPe: 19.8,
    pb: 1.58,
    peg: 1.45,
    evEbitda: 14.2,
    pcf: 15.0,
    roe: 13.8,
    roa: 6.8,
    operatingMargin: 19.5,
    grossMargin: 42.0,
    revenueGrowthYoY: 6.8,
    epsGrowthYoY: 14.5,
    debtToEquity: 0.28,
    currentRatio: 1.75,
    dividendYield: 0.0,
    payoutRatio: 0,
    rsi14: 56.0,
    beta: 0.65,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 510.00,
    fairValueUpside: 12.8,
    buffettScore: 98,
    investingProScore: 4.8,
    dalioScore: 94,
    growthScore: 65,
    valueScore: 84
  },
  {
    symbol: 'JPM',
    name: 'JPMorgan Chase & Co.',
    exchange: 'NYSE',
    country: 'US',
    sector: 'Finanza, Banche & Investment Banking',
    industry: 'Banks - Diversified',
    price: 212.00,
    changePct: 1.25,
    marketCap: 605.0,
    marketCapCategory: 'Mega',
    pe: 11.8,
    forwardPe: 11.2,
    pb: 1.82,
    peg: 1.20,
    evEbitda: 8.5,
    pcf: 7.8,
    roe: 17.5,
    roa: 1.4,
    operatingMargin: 45.8,
    grossMargin: 68.0,
    revenueGrowthYoY: 9.4,
    epsGrowthYoY: 15.2,
    debtToEquity: 0.85,
    currentRatio: 1.25,
    dividendYield: 2.2,
    payoutRatio: 26,
    rsi14: 62.5,
    beta: 0.84,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 245.00,
    fairValueUpside: 15.6,
    buffettScore: 90,
    investingProScore: 4.6,
    dalioScore: 85,
    growthScore: 74,
    valueScore: 86
  },
  {
    symbol: 'JNJ',
    name: 'Johnson & Johnson',
    exchange: 'NYSE',
    country: 'US',
    sector: 'Sanità, Farmaceutica & Dispositivi Medici',
    industry: 'Drug Manufacturers - General',
    price: 162.50,
    changePct: -0.20,
    marketCap: 390.0,
    marketCapCategory: 'Mega',
    pe: 17.2,
    forwardPe: 15.8,
    pb: 5.4,
    peg: 1.85,
    evEbitda: 13.0,
    pcf: 14.5,
    roe: 34.0,
    roa: 11.2,
    operatingMargin: 28.5,
    grossMargin: 69.2,
    revenueGrowthYoY: 4.5,
    epsGrowthYoY: 8.2,
    debtToEquity: 0.48,
    currentRatio: 1.22,
    dividendYield: 3.1,
    payoutRatio: 52,
    rsi14: 51.0,
    beta: 0.54,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 185.00,
    fairValueUpside: 13.8,
    buffettScore: 88,
    investingProScore: 4.3,
    dalioScore: 92,
    growthScore: 58,
    valueScore: 80
  },

  // 🇪🇺 EUROPA
  {
    symbol: 'ASML.AS',
    name: 'ASML Holding N.V.',
    exchange: 'Euronext Amsterdam',
    country: 'EU',
    sector: 'Semiconduttori & Litografia EUV',
    industry: 'Semiconductor Equipment',
    price: 765.00,
    changePct: 2.40,
    marketCap: 302.0,
    marketCapCategory: 'Mega',
    pe: 41.0,
    forwardPe: 28.5,
    pb: 18.5,
    peg: 1.55,
    evEbitda: 31.0,
    pcf: 35.0,
    roe: 49.5,
    roa: 18.4,
    operatingMargin: 32.8,
    grossMargin: 51.5,
    revenueGrowthYoY: 18.5,
    epsGrowthYoY: 28.0,
    debtToEquity: 0.32,
    currentRatio: 1.45,
    dividendYield: 1.0,
    payoutRatio: 35,
    rsi14: 58.2,
    beta: 1.28,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 920.00,
    fairValueUpside: 20.3,
    buffettScore: 91,
    investingProScore: 4.4,
    dalioScore: 72,
    growthScore: 94,
    valueScore: 52
  },
  {
    symbol: 'NOVO-B.CO',
    name: 'Novo Nordisk A/S',
    exchange: 'Nasdaq Copenhagen',
    country: 'EU',
    sector: 'Sanità & Trattamento Diabete/GLP-1',
    industry: 'Biotechnology',
    price: 815.00,
    changePct: 1.10,
    marketCap: 525.0,
    marketCapCategory: 'Mega',
    pe: 36.5,
    forwardPe: 29.0,
    pb: 32.0,
    peg: 1.40,
    evEbitda: 27.5,
    pcf: 30.0,
    roe: 88.0,
    roa: 36.5,
    operatingMargin: 45.2,
    grossMargin: 84.6,
    revenueGrowthYoY: 24.2,
    epsGrowthYoY: 31.5,
    debtToEquity: 0.40,
    currentRatio: 0.95,
    dividendYield: 1.3,
    payoutRatio: 48,
    rsi14: 53.5,
    beta: 0.62,
    priceAboveSma50: false,
    priceAboveSma200: true,
    fairValue: 960.00,
    fairValueUpside: 17.8,
    buffettScore: 93,
    investingProScore: 4.5,
    dalioScore: 80,
    growthScore: 95,
    valueScore: 58
  },
  {
    symbol: 'MC.PA',
    name: 'LVMH Moët Hennessy Louis Vuitton',
    exchange: 'Euronext Paris',
    country: 'EU',
    sector: 'Lusso, Moda & Gioielleria',
    industry: 'Luxury Goods',
    price: 642.00,
    changePct: -1.15,
    marketCap: 320.0,
    marketCapCategory: 'Mega',
    pe: 21.8,
    forwardPe: 19.5,
    pb: 4.9,
    peg: 1.65,
    evEbitda: 12.8,
    pcf: 15.2,
    roe: 26.2,
    roa: 10.8,
    operatingMargin: 26.5,
    grossMargin: 69.0,
    revenueGrowthYoY: 2.1,
    epsGrowthYoY: 5.5,
    debtToEquity: 0.45,
    currentRatio: 1.35,
    dividendYield: 2.0,
    payoutRatio: 42,
    rsi14: 42.0,
    beta: 0.95,
    priceAboveSma50: false,
    priceAboveSma200: false,
    fairValue: 780.00,
    fairValueUpside: 21.5,
    buffettScore: 89,
    investingProScore: 4.2,
    dalioScore: 78,
    growthScore: 68,
    valueScore: 76
  },
  {
    symbol: 'SAP.DE',
    name: 'SAP SE',
    exchange: 'XETRA Frankfurt',
    country: 'EU',
    sector: 'Enterprise Software & Cloud ERP',
    industry: 'Software - Application',
    price: 198.00,
    changePct: 1.65,
    marketCap: 232.0,
    marketCapCategory: 'Mega',
    pe: 38.0,
    forwardPe: 27.5,
    pb: 5.2,
    peg: 1.85,
    evEbitda: 22.0,
    pcf: 24.5,
    roe: 14.5,
    roa: 8.2,
    operatingMargin: 23.5,
    grossMargin: 72.8,
    revenueGrowthYoY: 10.5,
    epsGrowthYoY: 24.0,
    debtToEquity: 0.28,
    currentRatio: 1.25,
    dividendYield: 1.1,
    payoutRatio: 40,
    rsi14: 66.8,
    beta: 0.92,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 220.00,
    fairValueUpside: 11.1,
    buffettScore: 84,
    investingProScore: 4.1,
    dalioScore: 75,
    growthScore: 85,
    valueScore: 62
  },
  {
    symbol: 'TTE.PA',
    name: 'TotalEnergies SE',
    exchange: 'Euronext Paris',
    country: 'EU',
    sector: 'Energia, Petrolio & LNG',
    industry: 'Oil & Gas Integrated',
    price: 61.20,
    changePct: 0.40,
    marketCap: 145.0,
    marketCapCategory: 'Large',
    pe: 7.6,
    forwardPe: 7.1,
    pb: 1.18,
    peg: 0.78,
    evEbitda: 3.8,
    pcf: 4.2,
    roe: 19.5,
    roa: 7.5,
    operatingMargin: 16.2,
    grossMargin: 35.0,
    revenueGrowthYoY: -2.5,
    epsGrowthYoY: 4.8,
    debtToEquity: 0.38,
    currentRatio: 1.20,
    dividendYield: 5.8,
    payoutRatio: 45,
    rsi14: 52.0,
    beta: 0.76,
    priceAboveSma50: true,
    priceAboveSma200: true,
    fairValue: 76.00,
    fairValueUpside: 24.2,
    buffettScore: 81,
    investingProScore: 4.4,
    dalioScore: 87,
    growthScore: 55,
    valueScore: 92
  }
];

export const screenerDataService = {
  getPresetModels(): ScreenerPresetModel[] {
    return SCREENER_PRESET_MODELS;
  },

  getAllStocks(): ScreenerStockItem[] {
    return INITIAL_SCREENER_STOCKS.map(s => {
      const roic = s.roic ?? Number((s.roe * 0.82).toFixed(1));
      const fcfYield = s.fcfYield ?? Number(((100 / (s.pcf || 12)) * 0.88).toFixed(1));
      const piotroskiScore = s.piotroskiScore ?? Math.min(9, Math.max(3, Math.round(s.buffettScore / 11)));

      // 1. Technical Factor (35%)
      let tech = 50;
      if (s.priceAboveSma50) tech += 15;
      if (s.priceAboveSma200) tech += 15;
      if (s.rsi14 >= 45 && s.rsi14 <= 65) tech += 15;
      else if (s.rsi14 < 35) tech += 10;
      else if (s.rsi14 > 75) tech -= 10;
      if (s.beta >= 0.7 && s.beta <= 1.3) tech += 5;
      tech = Math.min(99, Math.max(15, tech));

      // 2. Fundamental Factor (40%)
      let fund = 50;
      if (s.fairValueUpside >= 25) fund += 25;
      else if (s.fairValueUpside >= 15) fund += 18;
      else if (s.fairValueUpside >= 5) fund += 8;
      else if (s.fairValueUpside < 0) fund -= 15;
      if (s.operatingMargin >= 20) fund += 12;
      if (s.roe >= 15) fund += 12;
      if (s.debtToEquity <= 0.8) fund += 10;
      if (s.pe > 0 && s.pe <= 18) fund += 10;
      fund = Math.min(99, Math.max(15, fund));

      // 3. AI Sentiment Factor (25%)
      let sent = Math.min(99, Math.max(25, Math.round((s.investingProScore / 5) * 80 + (s.changePct > 0 ? 14 : 4))));

      // Unified Composite Rank (0 to 100)
      const compositeRank = Math.round(tech * 0.35 + fund * 0.40 + sent * 0.25);

      return {
        ...s,
        roic,
        fcfYield,
        piotroskiScore,
        technicalScore: tech,
        fundamentalScore: fund,
        sentimentScore: sent,
        compositeRank
      };
    });
  },

  filterStocks(stocks: ScreenerStockItem[], filters: ScreenerFilterState): ScreenerStockItem[] {
    return stocks.filter(stock => {
      if (filters.search) {
        const query = filters.search.toLowerCase().trim();
        const matchSymbol = stock.symbol.toLowerCase().includes(query);
        const matchName = stock.name.toLowerCase().includes(query);
        const matchSector = stock.sector.toLowerCase().includes(query);
        if (!matchSymbol && !matchName && !matchSector) return false;
      }

      if (filters.minCompositeRank !== undefined && (stock.compositeRank ?? 0) < filters.minCompositeRank) {
        return false;
      }

      if (filters.country && filters.country !== 'ALL') {
        if (stock.country !== filters.country) return false;
      }

      if (filters.sector && filters.sector !== 'ALL') {
        if (!stock.sector.toLowerCase().includes(filters.sector.toLowerCase())) return false;
      }

      if (filters.marketCapCategory && filters.marketCapCategory !== 'ALL') {
        if (stock.marketCapCategory !== filters.marketCapCategory) return false;
      }

      if (filters.minPe !== undefined && stock.pe < filters.minPe) return false;
      if (filters.maxPe !== undefined && stock.pe > filters.maxPe) return false;

      if (filters.minPb !== undefined && stock.pb < filters.minPb) return false;
      if (filters.maxPb !== undefined && stock.pb > filters.maxPb) return false;

      if (filters.minPeg !== undefined && stock.peg < filters.minPeg) return false;
      if (filters.maxPeg !== undefined && stock.peg > filters.maxPeg) return false;

      if (filters.minRoe !== undefined && stock.roe < filters.minRoe) return false;
      if (filters.minRoic !== undefined && ((stock.roic ?? stock.roe * 0.85) < filters.minRoic)) return false;
      if (filters.minFcfYield !== undefined && ((stock.fcfYield ?? (100 / (stock.pcf || 15))) < filters.minFcfYield)) return false;
      if (filters.minPiotroskiScore !== undefined && ((stock.piotroskiScore ?? Math.min(9, Math.floor(stock.buffettScore / 11))) < filters.minPiotroskiScore)) return false;
      if (filters.minOperatingMargin !== undefined && stock.operatingMargin < filters.minOperatingMargin) return false;

      if (filters.minRevenueGrowth !== undefined && stock.revenueGrowthYoY < filters.minRevenueGrowth) return false;
      if (filters.minEpsGrowth !== undefined && stock.epsGrowthYoY < filters.minEpsGrowth) return false;

      if (filters.maxDebtToEquity !== undefined && stock.debtToEquity > filters.maxDebtToEquity) return false;
      if (filters.minCurrentRatio !== undefined && stock.currentRatio < filters.minCurrentRatio) return false;
      if (filters.minDividendYield !== undefined && stock.dividendYield < filters.minDividendYield) return false;
      if (filters.maxPayoutRatio !== undefined && stock.payoutRatio > filters.maxPayoutRatio) return false;

      if (filters.minFairValueUpside !== undefined && stock.fairValueUpside < filters.minFairValueUpside) return false;

      if (filters.minRsi !== undefined && stock.rsi14 < filters.minRsi) return false;
      if (filters.maxRsi !== undefined && stock.rsi14 > filters.maxRsi) return false;

      if (filters.smaTrend === 'ABOVE_200' && !stock.priceAboveSma200) return false;
      if (filters.smaTrend === 'ABOVE_50_200' && (!stock.priceAboveSma50 || !stock.priceAboveSma200)) return false;
      if (filters.smaTrend === 'BELOW_200' && stock.priceAboveSma200) return false;

      if (filters.minBeta !== undefined && stock.beta < filters.minBeta) return false;
      if (filters.maxBeta !== undefined && stock.beta > filters.maxBeta) return false;

      return true;
    });
  }
};
